FROM percona:5.6.32

# NOTE: This is not a production build: for sandbox/CI use only

# Set some default credentials to simplify usage
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=drupal
ENV MYSQL_PASSWORD=drupal
ENV MYSQL_DATABASE=drupal